agendapp/urls.py
from django.urls import path
from . import views

app_name = 'agendapp'
urlpatterns = [
    path('', views.IndexUserView.as_view(), name='index'),
    path('create/', views.CreateUserView.as_view(), name='create'),
    path('<int:pk>/edit/', views.EditUserView.as_view(), name='edit'),
    path('delete/<int:pk>', views.DeleteUserView.as_view(), name='delete')
]

agendaproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agendapp.urls'))
]

agendapp/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=30, help_text='30 caracteres max.')
    lastname = models.CharField(max_length=30, help_text='30 caracteres max.')
    phone = models.IntegerField(validators=[RegexValidator(r'^\d{6,10}$')], help_text='Min 6 - 10 caracteres max.')
    email = models.EmailField(max_length=30)

agendapp/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic

from .models import User


class SuccessMessageMixin:
    """
    Add a success message on successful form submission.
    """
    success_message = ''

    def form_valid(self, form):
        response = super().form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

class IndexUserView(generic.ListView):
    template_name = 'agendapp/index.html'
    context_object_name = 'users_list'

    def get_queryset(self):
        return User.objects.all()

class CreateUserView(SuccessMessageMixin, generic.CreateView):
    model = User
    fields = '__all__'
    template_name = 'agendapp/create.html'
    success_url = reverse_lazy('agendapp:index')
    success_message = "User %(name)s created!"

class EditUserView(SuccessMessageMixin, generic.UpdateView):
    model = User
    fields = '__all__'
    template_name = 'agendapp/edit.html'
    success_url = reverse_lazy('agendapp:index')
    success_message = "User %(name)s updated!"

class DeleteUserView(SuccessMessageMixin, generic.DeleteView):
    model = User
    success_url = reverse_lazy('agendapp:index')
    success_message = "User deleted!"

agendapp/templates/agendapp/base.html
<!doctype html>
<html lang="en">
  <!-- {% load static %} -->
  <head>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {# Load the tag library #}
    {% load bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <title>Agendapp</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

agendapp/templates/agendapp/create.html
{% extends 'agendapp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<br>

<div class="row">
  <div class="div.col-12.col-md-6.offset-md-3">
    <div class="card">
      <div class="card-body">
        <h1 class="mt-2">Create User</h1>
        <hr>
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <br>
          <hr>
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Crear</button>
            &nbsp;
            <a href="{% url 'agendapp:index' %}" class="btn btn-danger active" role="button"
              aria-pressed="true">Cancelar</a>
          </div>

        </form>
      </div>
    </div>


  </div>

  {% endblock %}

agendapp/templates/agendapp/edit.html
{% extends 'agendapp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="div.col-12.col-md-6.offset-md-3">
    <div class="card">
      <div class="card-body">
        <h1 class="mt-2">Edit User</h1>
        <hr>
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <br>
          <hr>

          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Save</button>
            &nbsp;
            <a href="{% url 'agendapp:index' %}" class="btn btn-danger active" role="button"
              aria-pressed="true">Cancel</a>
          </div>

        </form>
      </div>
    </div>


  </div>

  {% endblock %}

agendapp/templates/agendapp/index.html
{% extends 'agendapp/base.html' %}

{% block content %}
  <div align="left" class="btn_create mb-3">
  <a href="{% url 'agendapp:create' %}" type="button" class="btn btn-primary">Create User</a>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th width="50%">Name</th>
        <th width="50%">Last Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% if users_list %}
      {% for user in users_list %}
        <tr>
          <td>{{ user.name }}</td>
          <td>{{ user.lastname }}</td>
          <td>{{ user.phone }}</td>
          <td>{{ user.email }}</td>
          <td>
            <form method="POST" action="delete/{{user.id}}">
              {% csrf_token %}
              <div class="btn-group">
                <a href="{% url 'agendapp:edit' user.id %}" title="Editar" type="button" class="btn btn-primary">Edit</a>
                <button class="btn btn-danger" type="submit">
                  Delete
                </button>
              </div>
            </form>
          </td>
        </tr>
      {% endfor %}
    {% else %}
      <div class="alert alert-warning" role="alert">
        No user available.
      </div>
    {% endif %}
      </tbody>
    </table>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
    </div>
{% endblock %}